// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA0znvhLtb3gggmCyDiKVJUcHpAxMFT3A',
    appId: '1:1074732104067:android:e33b95ceef921e87aa9eb6',
    messagingSenderId: '1074732104067',
    projectId: 'patdoc-8e002',
    databaseURL: 'https://patdoc-8e002-default-rtdb.firebaseio.com',
    storageBucket: 'patdoc-8e002.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdXU94s5dVMfvhvDvbHr8lPRX93RMUdzk',
    appId: '1:1074732104067:ios:b799e67ea40714a3aa9eb6',
    messagingSenderId: '1074732104067',
    projectId: 'patdoc-8e002',
    databaseURL: 'https://patdoc-8e002-default-rtdb.firebaseio.com',
    storageBucket: 'patdoc-8e002.appspot.com',
    iosBundleId: 'com.horizons.patdoc.patdoc',
  );
}
